export const DISPLAY_ALERT = 'DISPLAY_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';

// User actions
export const  SETUP_USER = 'SETUP_USER';
export const SETUP_USER_END = 'SETUP_USER_END';

export const REGISTER_USER_BEGIN = 'REGISTER_USER_BEGIN';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';

export const LOGIN_USER_BEGIN = 'LOGIN_USER_BEGIN';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const LOGOUT_USER = 'LOGOUT_USER';

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';

export const DELETE_USER_BEGIN = 'DELETE_USER_BEGIN';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_ERROR = 'DELETE_USER_ERROR';

export const GET_SALDO_BEGIN = 'GET_SALDO';
export const GET_SALDO_SUCCESS = 'GET_SALDO_SUCCESS';
export const GET_SALDO_ERROR = 'GET_SALDO_ERROR';

// Transactions actions
export const GET_TRANSACTIONS_BEGIN = 'GET_TRANSACTIONS_BEGIN';
export const GET_TRANSACTIONS_SUCCESS = 'GET_TRANSACTIONS_SUCCESS';
export const GET_TRANSACTIONS_ERROR = 'GET_TRANSACTIONS_ERROR';

export const CREATE_TRANSACTION_BEGIN = 'CREATE_TRANSACTION_BEGIN';
export const CREATE_TRANSACTION_SUCCESS = 'CREATE_TRANSACTION_SUCCESS';
export const CREATE_TRANSACTION_ERROR = 'CREATE_TRANSACTION_ERROR';

export const UPDATE_TRANSACTION_BEGIN = 'UPDATE_TRANSACTION_BEGIN';
export const UPDATE_TRANSACTION_SUCCESS = 'UPDATE_TRANSACTION_SUCCESS';
export const UPDATE_TRANSACTION_ERROR = 'UPDATE_TRANSACTION_ERROR';

export const DELETE_TRANSACTION_BEGIN = 'DELETE_TRANSACTION_BEGIN';
export const DELETE_TRANSACTION_SUCCESS = 'DELETE_TRANSACTION_SUCCESS';
export const DELETE_TRANSACTION_ERROR = 'DELETE_TRANSACTION_ERROR';

// Conto actions
export const GET_CONTI_BEGIN = 'GET_CONTI_BEGIN';
export const GET_CONTI_SUCCESS = 'GET_CONTI_SUCCESS';
export const GET_CONTI_ERROR = 'GET_CONTI_ERROR';

export const CREATE_CONTO_BEGIN = 'CREATE_CONTO_BEGIN';
export const CREATE_CONTO_SUCCESS = 'CREATE_CONTO_SUCCESS';
export const CREATE_CONTO_ERROR = 'CREATE_CONTO_ERROR';

export const UPDATE_CONTO_BEGIN = 'UPDATE_CONTO_BEGIN';
export const UPDATE_CONTO_SUCCESS = 'UPDATE_CONTO_SUCCESS';
export const UPDATE_CONTO_ERROR = 'UPDATE_CONTO_ERROR';

export const DELETE_CONTO_BEGIN = 'DELETE_CONTO_BEGIN';
export const DELETE_CONTO_SUCCESS = 'DELETE_CONTO_SUCCESS';
export const DELETE_CONTO_ERROR = 'DELETE_CONTO_ERROR';

// Categorie actions
export const GET_CATEGORIE_BEGIN = 'GET_CATEGORIE_BEGIN';
export const GET_CATEGORIE_SUCCESS = 'GET_CATEGORIE_SUCCESS';
export const GET_CATEGORIE_ERROR = 'GET_CATEGORIE_ERROR';

export const CREATE_CATEGORIA_BEGIN = 'CREATE_CATEGORIA_BEGIN';
export const CREATE_CATEGORIA_SUCCESS = 'CREATE_CATEGORIA_SUCCESS';
export const CREATE_CATEGORIA_ERROR = 'CREATE_CATEGORIA_ERROR';

export const UPDATE_CATEGORIA_BEGIN = 'UPDATE_CATEGORIA_BEGIN';
export const UPDATE_CATEGORIA_SUCCESS = 'UPDATE_CATEGORIA_SUCCESS';
export const UPDATE_CATEGORIA_ERROR = 'UPDATE_CATEGORIA_ERROR';

export const DELETE_CATEGORIA_BEGIN = 'DELETE_CATEGORIA_BEGIN';
export const DELETE_CATEGORIA_SUCCESS = 'DELETE_CATEGORIA_SUCCESS';
export const DELETE_CATEGORIA_ERROR = 'DELETE_CATEGORIA_ERROR';

